### ISSUE TITLE
Find out if a login/consent challenge is still valid

### ISSUE THREAD

**Issue by dlarsson** [ory/hydra#2057]
**Login and consent challenges time out, but I haven't found a way to determine if this has happened**

After being redirected to the login and consent pages, you're given a login/consent challenge. After the user has somehow authenticated himself, the login/consent session is accepted to hydra with the given login/consent challenge. However, if this takes too long (I believe it's a 10 minute timeout by default?), an error is returned, and the login attempt fails.

To avoid "detecting" this *after* the user has tried to authenticate himself, only to get redirected back to the client application, which presumably redirects you back to the login screen (via hydra), I would have liked to be able to poll the status of the challenge, and reject the login request if the user is slow.

**Describe the solution you'd like**

It would be great if the GET /oauth2/auth/requests/{login, consent} endpoints could indicate if the challenge is still valid or not. As far as I can tell, they still return the same information regardless if the challenge has timed out or not.

**Describe alternatives you've considered**

The alternative is obviously to have my own timer, shorter than whatever challenge timer is configured in hydra, and do this rejection myself. I would just be much cleaner and nicer if hydra could give me this info. I'm sure it could easily provide it (?).

**Comment by pjediny** [comment]
I was wondering about this too + there is a difficulty when your challenge expire, that you know nothing about the context in which the login was triggered, so you cannot reflow user via proper client. I think this can be work around by using own session management in login&consent application.

**Comment by dlarsson** [comment]
I'm pretty sure the accept/reject login calls return a redirect_uri back to the proper client. So this should work fine, unless I misunderstood your last point.

**Comment by aeneasr** [comment]
> I'm pretty sure the accept/reject login calls return a redirect_uri back to the proper client. So this should work fine, unless I misunderstood your last point.

Exactly! There is also `request_url` which is the original URL that was requested

**Comment by pjediny** [comment]
@aeneasr I did not realise I could accept/reject with invalid challenge and get the redirect_uri data back?

**Comment by dlarsson** [comment]
@pjediny It seems the challenge isn't (immediately) removed from hydra at timeout, as I'm still able to GET  /oauth2/auth/requests/{login, consent} after it has timed out, and get the correct data back. And as you say, it would need to be retained longer to be able to return back to the original client.

**Comment by pjediny** [comment]
Maybe, but the questions still stand - just in slightly different context:
- What would happen when the challenge is removed from hydra?
- When it is removed?
- Is it documented somewhere?

What would be recommended approach to recover from such situation?

**Comment by aeneasr** [comment]
The challenge isn't removed automatically, but if I recall correctly it will be removed when you call the flush command!

**Comment by verzac** [comment]
Hey team,

Is there already work done for this? Currently being hit by the same issue (either that or my perception of time was slightly bended).

I initially check whether or not the login challenge is valid through the admin client (in the Go SDK: `a.Admin.GetLoginRequest`), and everything seems to work just fine - no 4xx or 5xx or any other funky status codes. However, when I try to redirect the user using the value in `redirect_to`, it redirects to an error page which says "The request could not be authorized. The login request has expired. Please try again."

Scoured a bit through the Go SDK and the REST API docs, and I couldn't find any explicit mention of this or how to check whether or not the login challenge has timed out. Would love a de-facto way to do this properly :)

**Comment by aeneasr** [comment]
Closing as resolved in #2473

**Comment by martinei** [comment]
I still don't see how it is possible to find out if a challenge has expired. the https://github.com/ory/hydra/pull/2473 only handles already used challenges, not expired ones.

**Comment by aeneasr** [comment]
True, we don't handle the expired case yet, only reuse

**Comment by terev** [comment]
Just ran into this. I assumed 410 would be returned for expired challenges too. Without this the best thing I can think to do is identify this error class and inform the user agent somehow, so it can restart the login flow. Unfortunately we can't even get the original redirect url to redirect to for handling this error at the moment.
