### ISSUE TITLE
The DB mitigation status should not be checked for /health/ready

### ISSUE THREAD

**Issue by shoujun** [ory/hydra#3300]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The DB mitigation status check was added on March 7th, 2021, this check added more than 200 of sql-xxx actions, an extra 5+ seconds in average added to this endpoint check.

It seems not neccessary to check the DB mitigation status every time.

### Reproducing the bug

Start up a hydra instance with connected to DB
Access /health/ready
Check the logs
![Screen Shot 2022-10-18 at 10 59 25 AM](https://user-images.githubusercontent.com/21117823/196468132-66d2326a-465a-4d09-b966-27a1cc229b2b.png)

### Version

1.11.10

**Comment by aeneasr** [comment]
This is fixed on master!

**Comment by shoujun** [comment]
I am refering this code range in master:
https://github.com/ory/hydra/blob/master/driver/registry_base.go#L264-L290
It seems not fixed yes, do I look at the correct place?

**Comment by aeneasr** [comment]
It is fixed, the result is cached:

- https://github.com/ory/hydra/blob/master/driver/registry_base.go#L271
- https://github.com/ory/hydra/blob/master/driver/registry_base.go#L286

**Comment by aeneasr** [comment]
Yes it has!
